name: notification_notes
description: Notification notes app

version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  flutter_local_notifications: ^6.0.0
  flutter_slidable: ^0.6.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
